name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          NUTRITIONIX_APP_ID: ${{ secrets.NUTRITIONIX_APP_ID }}
          NUTRITIONIX_API_KEY: ${{ secrets.NUTRITIONIX_API_KEY }}
        run: |
          echo "HUGGINGFACE_TOKEN=$HUGGINGFACE_TOKEN" > .env
          echo "NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID" >> .env
          echo "NUTRITIONIX_API_KEY=$NUTRITIONIX_API_KEY" >> .env
          cat .env

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-virtualenv git zip unzip openjdk-11-jdk \
          android-sdk adb curl build-essential autoconf automake libtool pkg-config zlib1g-dev libncurses5 libncurses5-dev libffi-dev libssl-dev

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython python-dotenv

      - name: Setup Java environment
        run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: caloreyes-apk
          path: bin/*.apk
