name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      NUTRITIONIX_APP_ID: ${{ secrets.NUTRITIONIX_APP_ID }}
      NUTRITIONIX_API_KEY: ${{ secrets.NUTRITIONIX_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            build-essential libncurses5 libstdc++6 libffi-dev \
            libssl-dev libsqlite3-dev zlib1g-dev ant curl

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools Cython
          pip install buildozer

      - name: Prepare environment
        run: |
          echo "Creating .env file from secrets"
          cat <<EOF > .env
HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
NUTRITIONIX_APP_ID=${NUTRITIONIX_APP_ID}
NUTRITIONIX_API_KEY=${NUTRITIONIX_API_KEY}
EOF

      - name: Initialize Buildozer (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Set correct ant path in buildozer.spec
        run: |
          sed -i 's|^#* *android.ant_path *=.*|android.ant_path = /usr/bin/ant|' buildozer.spec

      - name: Build APK
        run: |
          buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: caloreyes-apk
          path: bin/*.apk
          if-no-files-found: error
