name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          NUTRITIONIX_APP_ID: ${{ secrets.NUTRITIONIX_APP_ID }}
          NUTRITIONIX_API_KEY: ${{ secrets.NUTRITIONIX_API_KEY }}
        run: |
          echo "HUGGINGFACE_TOKEN=$HUGGINGFACE_TOKEN" > .env
          echo "NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID" >> .env
          echo "NUTRITIONIX_API_KEY=$NUTRITIONIX_API_KEY" >> .env
          cat .env

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools python3-virtualenv git zip unzip openjdk-11-jdk \
            adb curl build-essential autoconf automake libtool pkg-config zlib1g-dev \
            libncurses-dev libffi-dev libssl-dev wget unzip

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython python-dotenv

      - name: Setup Java environment
        run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Download and install Android SDK command line tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools latest

      - name: Set Android SDK environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses and install SDK packages
        run: |
          yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
          sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Export Android SDK tools paths
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$PATH" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: caloreyes-apk
          path: bin/*.apk
